---
language: node_js
node_js:
  - "0.12"

sudo: required

cache:
  directories:
    - node_modules

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.4.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - npm config set spin false
  - npm install -g npm@^2
  - wget https://github.com/mbarberot/sistearth-backend/archive/master.zip
  - unzip master.zip
  - bash prepare-test.sh


install:
  - npm install -g bower
  - npm install
  - bower install
  - docker-compose up -d && sleep 20

script:
  - npm test
